Obj id bitmask endpoint
ome/omero-web pull request #308
Opened 2021-08-05 12:37 UTC by kkoz

This PR adds an endpoint to make label image data retrieval more efficient from omero tables. Rather than returning the entire result of a query which could be a very large number of objects, the endpoint returns a bitmask representing the object IDs, where the bit is set to 1 if that ID matched the query and 0 otherwise. You can hit the endpoint using a URL like `http://localhost/webgateway/table/123/obj_id_bitmask/?query=value<14`. A `col_name` parameter can also be passed if your object ID column name is not named `object`

2021-08-06 00:41 UTC, snoopycrimecop commented
Conflicting PR. Removed from build [OMERO-python-superbuild-push#779](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/779/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/779/consoleText) for more details.
Possible conflicts:
  - PR #270 will-moore 'constrain plate grid'
    - omeroweb/webgateway/views.py
  - PR #300 will-moore 'Improve OMERO.table download usability'
    - omeroweb/webgateway/views.py
  - PR #305 kkoz 'Only return the column names that were requested'
    - omeroweb/webgateway/views.py

--conflicts

2021-08-09 21:17 UTC, will-moore commented on omeroweb/webgateway/views.py
> +        while index < obj_id:
In my case, the first column in this row is a 'StringColumn', so that `obj_id` is a string (and this comparison line fails).

2021-08-10 00:40 UTC, snoopycrimecop commented
Conflicting PR. Removed from build [OMERO-python-superbuild-push#783](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/783/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/783/consoleText) for more details.
Possible conflicts:
  - PR #270 will-moore 'constrain plate grid'
    - omeroweb/webgateway/views.py
  - PR #300 will-moore 'Improve OMERO.table download usability'
    - omeroweb/webgateway/views.py
  - PR #305 kkoz 'Only return the column names that were requested'
    - omeroweb/webgateway/views.py

--conflicts

2021-08-13 00:40 UTC, snoopycrimecop commented
Conflicting PR. Removed from build [OMERO-python-superbuild-push#786](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/786/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/786/consoleText) for more details.
Possible conflicts:
  - PR #270 will-moore 'constrain plate grid'
    - omeroweb/webgateway/views.py
  - PR #300 will-moore 'Improve OMERO.table download usability'
    - omeroweb/webgateway/views.py

--conflicts

2021-08-14 00:39 UTC, snoopycrimecop commented
Conflicting PR. Removed from build [OMERO-python-superbuild-push#787](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/787/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/787/consoleText) for more details.
Possible conflicts:
  - PR #270 will-moore 'constrain plate grid'
    - omeroweb/webgateway/views.py
  - PR #300 will-moore 'Improve OMERO.table download usability'
    - omeroweb/webgateway/views.py

--conflicts

2021-08-17 14:11 UTC, kkoz commented
@will-moore Is there something I can or should do on this PR to resolve SCC's conflict comments?

2021-08-17 15:13 UTC, will-moore commented
Apologies: I meant to ping @chris-allan and @erindiel for final feedback on those (#270 and #300) but I think they should be close to getting merged.
In the meantime, I can test this PR again locally...

2021-08-17 15:34 UTC, will-moore commented
Testing locally with a table where this URL `/webgateway/table/68129/query/?query=Count<400` gives me...

<details><summary>this JSON</summary>

```
{
"data": {
    "column_types": [
        "StringColumn",
        "DoubleColumn",
        "DoubleColumn",
        "DoubleColumn",
        "DoubleColumn",
        "DoubleColumn",
        "DoubleColumn",
        "DoubleColumn",
        "DoubleColumn",
        "DoubleColumn",
        "DoubleColumn",
        "DoubleColumn",
        "DoubleColumn",
        "StringColumn",
        "DoubleColumn",
        "DoubleColumn",
        "ImageColumn"
    ],
    "columns": [
        "Slice",
        "Count",
        "Total_Area",
        "Average_Size",
        "%Area",
        "Mean",
        "Mode",
        "Perim.",
        "Feret",
        "FeretX",
        "FeretY",
        "FeretAngle",
        "MinFeret",
        "Dataset",
        "Bounding_Box",
        "Channel_Index",
        "Image"
    ],
    "rows": [
        [
            "c:1/2 - PCNT_gtub_I_044_SIR_PRJ.dv",
            200,
            74.26790595054626,
            37.13395297527313,
            72.6318359375,
            0,
            0,
            341.06953144073486,
            92.94512271881104,
            12900,
            11050,
            8191.774749755859,
            62.0566189289093,
            "PCNT-N1",
            177.86849737167358,
            100,
            1101
        ],
        [
            "c:2/2 - N20_PCNTab_ctrl_20110618_Sat-1400_0_SIR_PRJ.dv",
            200,
            46.88798189163208,
            23.44399094581604,
            45.623779296875,
            0,
            0,
            197.2864270210266,
            63.870203495025635,
            10800,
            10750,
            13633.149719238281,
            55.110132694244385,
            "PCNT-N1",
            42.66819953918457,
            200,
            1091
        ],
        [
            "c:1/2 - PCNT_gtub_I_010_SIR_PRJ.dv",
            300,
            55.70092797279358,
            18.566976487636566,
            54.473876953125,
            0,
            0,
            145.4495906829834,
            52.599912881851196,
            13933.332824707031,
            12633.333587646484,
            4308.696746826172,
            32.88620710372925,
            "PCNT-N1",
            85.24099588394165,
            100,
            1106
        ],
        ...
```
</details>

When I use: `/webgateway/table/68129/obj_id_bitmask/?query=Count<400&col_name=Image` I get:

```
{
"message": "byte must be in range(0, 256)",
"stacktrace": "Traceback (most recent call last):\n  File \"/Users/wmoore/Desktop/WEB/omero-web/omeroweb/webgateway/views.py\", line 1431, in wrap\n    rv = f(request, *args, **kwargs)\n  File \"/Users/wmoore/Desktop/WEB/omero-web/omeroweb/webgateway/views.py\", line 3125, in obj_id_bitmask\n    data.append(value)\nValueError: byte must be in range(0, 256)\n"
}
```

So either I'm not understanding the usage or my data is not as expected?

2021-08-18 00:38 UTC, snoopycrimecop commented
Conflicting PR. Removed from build [OMERO-python-superbuild-push#790](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/790/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/790/consoleText) for more details.
Possible conflicts:
  - PR #270 will-moore 'constrain plate grid'
    - omeroweb/webgateway/views.py
  - PR #300 will-moore 'Improve OMERO.table download usability'
    - omeroweb/webgateway/views.py

--conflicts

2021-08-19 14:43 UTC, will-moore commented
So, the URL I was testing above `/webgateway/table/68129/obj_id_bitmask/?query=Count<400&col_name=Image`  is now downloading something.
Do you have any sample code to help me validate whether this is correct? thx.

2021-08-23 15:30 UTC, kkoz commented
@will-moore I've put a test script I wrote here: https://gist.github.com/kkoz/791555afe60bc8dc6a4cd6c3c57988ed
Run this script against a table with an 'object' column and you should get back a bitmask where the bit is set to 1 if the object ID is returned by your query or 0 otherwise. E.g. if you had object IDs 0, 1, 3, 9, 22, and 23 and used the query `object < 10` you should get back `1101000001000000` (there will probably be some extra 0s at the end). Let me know if that works for you

2021-08-23 21:37 UTC, will-moore commented
I'm not sure if I understand your example:
```
>>> ids = [0, 1, 3, 9, 22, 23]
>>> ''.join(["1" if id < 10 else "0" for id in ids])
'111100'
```
not `1101000001000000` (even with some padding)?

I'm adding a test which should help us run the same tests.
I didn't manage to get your gist working (kept getting the login page returned - maybe using wrong sessionid) but the code sample was useful for writing a test.

Test added at https://github.com/ome/openmicroscopy/pull/6289

2021-08-24 12:09 UTC, kkoz commented
@will-moore The sessionid is supposed to be a omero web session ID, the one stored as the 'sessionid' cookie in the browser. Sorry I should have specified that.

2021-08-25 10:55 UTC, chris-allan requested changes
As this is going into the public API at a minimum we need an extensive docstring in `urls.py` describing what the intent is here and what the caller can be expected to receive. Things like endianness, padding, and the layout of the bytes need to be explicitly defined.

Furthermore, some unit tests at least enforcing the byte layout need to be added. This probably necessitates refactoring the logic for producing the resulting bytes out of the view method.

2021-08-25 10:55 UTC, chris-allan commented on omeroweb/webgateway/views.py
> +    for obj in rsp_data["data"]["rows"]:
I know you've spent the effort here already to do the bit twiddling and masking but for readability and given that `numpy` is already an OMERO.web dependency it's probably worthwhile to use a numpy array and packbits [1] to create your bytes to return.

  1. https://numpy.org/doc/stable/reference/generated/numpy.packbits.html

2021-08-25 14:05 UTC, will-moore commented on omeroweb/webgateway/views.py
> +    for obj in rsp_data["data"]["rows"]:
That reminds me of the BinData discussion we had for Masks, where we eventually decided not to use `numpy.packbits`: https://github.com/ome/ome-model/pull/140
But that was proposing a much wider-ranging breaking change, so I think it's different from this case.

2021-08-30 17:53 UTC, kkoz commented on omeroweb/webgateway/views.py
> +    for obj in rsp_data["data"]["rows"]:
I'm not really sure how packbits or unpackbits would help here. I'm not doing a conversion from binary to integer or vice versa. The values returned from the query are used as the indices for the bits to be flipped in the bytearray. @chris-allan could you elaborate on how you see packbits being used here? I'm also unsure about how to use the comment you linked. We don't have n-dimensional arrays, aren't really doing any padding, and aren't interacting with OME-TIFF files. As far as padding,I can add to the docstring that the endpoint will return the number of bytes required to accurately reflect the query result, but there isn't any fixed response size we are padding to. As far as endianness, I don't really see where that comes into play here since the response only really makes sense when processed one byte (or bit) at a time.

2021-08-31 10:58 UTC, chris-allan commented on omeroweb/webgateway/views.py
> +    for obj in rsp_data["data"]["rows"]:
> I'm not really sure how packbits or unpackbits would help here. I'm not doing a conversion from binary to integer or vice versa.

Are you not? Your return value is bit packed uint8 array with the object IDs that match your query toggled on. If you had 10 rows, and rows at index 0, 3, and 7 matched this would be your array for `packbits()`:

`[1, 0, 0, 1, 0, 0, 0, 1]`

You can conveniently pack this without performing any bitwise operations:

```
...
In [3]: numpy.packbits([1, 0, 0, 1, 0, 0, 0, 1])
Out[3]: array([145], dtype=uint8)
```

If you wanted to work with your resultant array in Python you would use `unpackbits()`:

```
...
In [9]: numpy.unpackbits(numpy.array([145], dtype=numpy.uint8))
Out[9]: array([1, 0, 0, 1, 0, 0, 0, 1], dtype=uint8)
```

> We don't have n-dimensional arrays, aren't really doing any padding, and aren't interacting with OME-TIFF files. As far as padding,

You're right that we don't have n-dimensional arrays here and aren't interacting with OME-TIFF files however the issues discussed in ome/ome-model#140 are very important to consumers of the result this code produces. Your array of bits is always going to consume a number of bytes required to pack even if the number of bits you are trying to encode is not divisible by 8. Currently you are, by default, performing 0 padding:

```
In [10]: a = numpy.packbits([0, 1, 0, 1])

In [11]: print(a)
[80]

In [12]: b = numpy.unpackbits(a)

In [13]: print(b)
[0 1 0 1 0 0 0 0]
```

Endianness matters to the consumer here as you must know the bit encoding order. Right now it's big endian but you need to state that as it could just as easily be little. This is doubly important for the byte at the end that may be 0 padded.

> ...but there isn't any fixed response size we are padding to...

As above and as you've said yourself, yes there is. Your return value is currently 0 padded to the nearest byte if required.

2021-08-31 13:44 UTC, chris-allan commented on omeroweb/webgateway/views.py
> +    packed = numpy.packbits(bitArray, bitorder='big')
Would `tobytes()` [1] work here?

  1. https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tobytes.html#numpy-ndarray-tobytes

2021-09-06 13:59 UTC, will-moore commented
Updated the test at https://github.com/will-moore/openmicroscopy/commit/8b0991d452e2278a00896246d1b45f2fd20d9010 to correspond with the usage of `numpy.packbits()` above.

2021-11-04 13:15 UTC, sbesson commented
@chris-allan could you also update your previous review https://github.com/ome/omero-web/pull/308#pullrequestreview-738196240.

No objections to getting this merged from my side. I have two follow-up questions regarding the versioning and distribution:
-  I assume the development version number could be immediately incremented to `5.12.0.dev0`  to communicate that a new backwards compatible API and endpoint have been introduced in the main development line
- should this feature be released immediately or can we define a roadmap towards OMERO.web 5.12.0?

2021-11-04 13:43 UTC, chris-allan approved these changes

2021-11-04 13:47 UTC, chris-allan commented
> I assume the development version number could be immediately incremented to 5.12.0.dev0 to communicate that a new backwards compatible API and endpoint have been introduced in the main development line

Certainly.

> should this feature be released immediately or can we define a roadmap towards OMERO.web 5.12.0?

Unless there's a really compelling reason not to, from our side it would be really nice to have this released.

2021-11-09 15:56 UTC, merged