Show fileset ID
ome/omero-web pull request #385
Opened 2022-07-22 11:06 UTC by will-moore

See https://github.com/ome/omero-cli-zarr/pull/123#pullrequestreview-1032712957

It is useful for webclient users to see the Fileset ID for a selected Image.
We already load fileset info (file paths) in a file-paths info panel, so this seems a logical place to load and display fileset ID:

The tooltip for the button that launches this panel also mentions Fileset ID.

<img width="361" alt="Screenshot 2022-07-22 at 12 04 40" src="https://user-images.githubusercontent.com/900055/180426616-35a5882a-d83a-45c3-b1d3-32292b239585.png">

2022-07-29 13:12 UTC, sbesson commented
Thanks, I am unaware of an alternate location in the web client which would expose Fileset information and would be more suitable.

Do we foresee adding more metadata about the fileset in the future? In this case, would it make sense to structure the top-level panel similarly to other elements i.e.

```
Fileset ID: <id>
Owner: <owner name>
File count: <count>
```

2022-08-01 22:12 UTC, will-moore commented
I don't think we need to show the Owner (can't imagine it's different from the Image owner very often) and the File count is already shown.

2022-08-02 12:24 UTC, pwalczysko commented
Works as expected with multi- and single-file filesets.
Maybe RFE would be to do one of the following:
1. de-capitalize the word "Image" in the "Image file", see screenshot (because the capital image is not proper imho as well as it suggests that the important bit here is an "Image", whereas the number shows number of **files**
2. Go partially for the suggestion of @sbesson in https://github.com/ome/omero-web/pull/385#issuecomment-1199269707 - I would also leave the "Owner" info out though, as it will add too much burden on the dialog unecessarily

I realize this is not a topic of this PR, but the whole header of the "Paths" dialog could do with some reformatting and unification
![Screenshot 2022-08-02 at 13 20 16](https://user-images.githubusercontent.com/2478303/182373829-2677cf67-448d-4cde-a8f1-a341450e454b.png)

2022-08-02 12:29 UTC, pwalczysko requested changes
Please address https://github.com/ome/omero-web/pull/385#issuecomment-1202419052

2022-08-02 12:58 UTC, will-moore commented
Last commit looks like this:

![Screenshot 2022-08-02 at 13 57 44](https://user-images.githubusercontent.com/900055/182380419-05bfb797-7ca6-4fe6-a0c7-c1df325a531e.png)

2022-08-03 12:55 UTC, pwalczysko approved these changes

2022-08-06 01:34 UTC, merged