Upgraded omero-web dependencies
ome/omero-web pull request #433
Opened 2023-01-05 14:06 UTC by kyleBalisWest

Upgraded omero-web jquery dependencies. See [upgrade spreadsheet](https://docs.google.com/spreadsheets/d/1t4OS7DEjTtjPJVOZZkRlbtZtB_5F-krGILroVKD5pRc/edit?usp=sharing) for a detailed list of changes.

2023-01-05 15:27 UTC, sbesson commented on omeroweb/webgateway/static/3rdparty/jquery-ui-1.13.2/css/jquery-ui.css
> +/*! jQuery UI - v1.13.2 - 2022-12-06
As we are upgrading jquery-ui, 2 questions:

- can we use the opportunity to fix https://github.com/ome/omero-web/issues/333 which causes periodic errors in the nginx logs due to the lack of images
- as suggested in the comment above, the previous version included manual edits - see https://github.com/ome/omero-web/issues/333#issuecomment-969174368 for the relevant comments. Do we have an authoritative list of the places that were affected by these custom changes or would we expect this to be picked up as part of the OMERO.web testing?

2023-01-05 15:27 UTC, sbesson commented on omeroweb/settings.py
>                  "3rdparty/jquery-ui-1.10.4/js/jquery-ui.1.10.4.js",
Same comment as above

2023-01-05 15:48 UTC, kyleBalisWest commented on omeroweb/webgateway/static/3rdparty/jquery-ui-1.13.2/css/jquery-ui.css
> +/*! jQuery UI - v1.13.2 - 2022-12-06
@sbesson I'm not sure about the first question but for the second one I forgot to write what was effected by the custom changes but I did put what the custom changes I made. Mostly they had to do with the tabs and background of the right hand panel if I remember correctly.

2023-01-05 16:04 UTC, sbesson commented on omeroweb/webgateway/static/3rdparty/jquery-ui-1.13.2/css/jquery-ui.css
> +/*! jQuery UI - v1.13.2 - 2022-12-06
For the first comment, I think the problem is that the jquery-ui CSS links to images which were not included in the former library upgrade e.g. in https://github.com/ome/omero-web/blob/v5.16.0/omeroweb/webgateway/static/3rdparty/jquery-ui-1.12.1/css/jquery-ui.css#L1094. This in turns leads to errors when these images are being requested.

Is this still the case for `jquery-ui 1.13.*` and if so, should the `images` be reincluded like panojs?

2023-01-05 19:25 UTC, kyleBalisWest commented on omeroweb/webgateway/static/3rdparty/jquery-ui-1.13.2/css/jquery-ui.css
> +/*! jQuery UI - v1.13.2 - 2022-12-06
Okay, I think I see what you mean. I added in the missing images to fix that problem.

2023-01-05 20:01 UTC, kyleBalisWest commented on omeroweb/settings.py
>                  "3rdparty/jquery-ui-1.10.4/themes/base/jquery-ui.all.css",
Yeah that is interesting. I tried fixing it to see if jquery-ui is loaded to the browser differently since it might be compressed with pipeline but I didn't see a difference.

2023-01-18 10:54 UTC, chris-allan commented
Not important right now while we're iterating but I would suggest that before this is merged we get all detail out of the Google Spreadsheet as Markdown and into the description of this PR. We will need the content in that form for a migration guide and/or changelog anyway.

2023-01-18 15:57 UTC, will-moore commented on omeroweb/webgateway/static/3rdparty/panojs-3.0.0/PanoJS.js
> +  this.tileSize = (options.tileSize ? options.tileSize : PanoJS.TILE_SIZE);
It looks like `PanoJs(viewer, options)` no-longer supports `options.xTileSize` and `options.yTileSize`?
So in our usage of `PanoJS` we'll need to use `options.tileSize` instead, which should be fine for when tile size x and y is the same, but I think there are cases when this isn't true. I don't have a feel for how often this occurs or if there's any way to support it (except maybe not upgrading)?

2023-01-18 21:35 UTC, kyleBalisWest commented on omeroweb/webgateway/static/3rdparty/panojs-3.0.0/PanoJS.js
> +  this.tileSize = (options.tileSize ? options.tileSize : PanoJS.TILE_SIZE);
Oh interesting, that's a good point. I don't know much about pyramidal data, so I was wondering how often does the xTileSize and yTileSize differ?

Though, if you don't want to upgrade it should be an easy switch back.

2023-01-19 10:47 UTC, will-moore commented
I'm afraid jQuery-UI auto-complete is still off (mapr):

![Screenshot 2023-01-19 at 10 25 49](https://user-images.githubusercontent.com/900055/213418681-b116eab0-33fd-4946-9dda-1a3ce97cbc3a.png)

It looks like this is due to the previous jQuery-ui having a `display: block` on the `<a>`

![Screenshot 2023-01-19 at 10 40 56](https://user-images.githubusercontent.com/900055/213422369-fdeb66a4-4619-4330-9e01-463bf310a4c7.png)

Whereas there is no such rule in the updated version:
![Screenshot 2023-01-19 at 10 43 56](https://user-images.githubusercontent.com/900055/213422459-7a1c453f-828f-487e-b263-6fb5002ad048.png)

Probably easiest fix is to add `display: block` to that `dusty.css` under `.ui-menu-item a`?

2023-01-19 10:52 UTC, jburel commented
* Preview tab (right-hand panel)
   * when moving the right-hand side of the slider knob to the left, the knob always moves back to the full range after release

2023-01-19 10:54 UTC, will-moore commented
@jburel I think that sounds like expected behaviour if the right slider value is above the max intensity, the slider will update it's upper limit to be the max of the current slider value or the max intensity value.

2023-01-19 11:01 UTC, pwalczysko commented on omeroweb/webgateway/static/3rdparty/panojs-3.0.0/PanoJS.js
> +  this.tileSize = (options.tileSize ? options.tileSize : PanoJS.TILE_SIZE);
@kyleBalisWest Often enough, see example in https://github.com/ome/omero-web/pull/433#issuecomment-1396786819 please :)

2023-01-19 11:57 UTC, jburel commented
> @jburel I think that sounds like expected behaviour if the right slider value is above the max intensity, the slider will update it's upper limit to be the max of the current slider value or the max intensity value.

The problem was noticed when using https://merge-ci.openmicroscopy.org/web/webclient/?show=image-236165

2023-01-19 12:41 UTC, will-moore commented
@pwalczysko For me, the old viewer with that image looks a bit different - Maybe you've got some tiles cached? Anyway, it's also due to Pano.js: In this case the tiles are square: ```"tile_size": {
"width": 1024,
"height": 1024
},```, so it could be fixed by passing Pano.js the correct (new) options, but I think we need to roll back the Pano.js upgrade anyway, to support non-square tiles of other images.

2023-01-19 12:52 UTC, pwalczysko commented
> @pwalczysko For me, the old viewer with that image looks a bit different - Maybe you've got some tiles cached? Anyway, it's also due to Pano.js: In this case the tiles are square: `"tile_size": { "width": 1024, "height": 1024 },`, so it could be fixed by passing Pano.js the correct (new) options, but I think we need to roll back the Pano.js upgrade anyway, to support non-square tiles of other images.

No, I tried to clear cache and also a new browser, the problem persists. The issue here might be that I have zoomed in a little, otherwise the problem does not manifest.

2023-01-23 12:11 UTC, pwalczysko commented
There are still some issues with icons on the Preview pane, see for example images such as https://merge-ci.openmicroscopy.org/web/webclient/?show=image-146365 

The icons on merge-ci

![Screenshot 2023-01-23 at 12 08 47](https://user-images.githubusercontent.com/2478303/214036182-e82945a8-ee2b-4b09-845c-9685601b3386.png)


The icons on lates-ci

![Screenshot 2023-01-23 at 12 09 47](https://user-images.githubusercontent.com/2478303/214036423-d3687b32-f211-4397-9020-6124616512ef.png)


And errors in the Console

![Screenshot 2023-01-23 at 12 11 32](https://user-images.githubusercontent.com/2478303/214036685-6078e3d0-d823-4763-bcdc-eaf76097519b.png)

2023-01-23 12:41 UTC, will-moore commented
@kyleBalisWest I think the zoom icons are missing (see Petr's screenshot) due to this diff in the reverting of Pano.js (last commit):

```
--- a/omeroweb/webgateway/static/3rdparty/panojs-3.0.0/controls.js
+++ b/omeroweb/webgateway/static/3rdparty/panojs-2.0.0/controls.js
@@ -10,15 +10,15 @@
 
 *******************************************************************************/
 
-PanoJS.CONTROL_IMAGE_ZOOMIN   = "images/32px_plus.png";
-PanoJS.CONTROL_IMAGE_ZOOM11   = "images/32px_11.png";
-PanoJS.CONTROL_IMAGE_ZOOMOUT  = "images/32px_minus.png";
-PanoJS.CONTROL_IMAGE_MAXIMIZE = "images/32px_show.png";
+PanoJS.CONTROL_IMAGE_ZOOMIN   = "32px_plus.png";
+PanoJS.CONTROL_IMAGE_ZOOM11   = "32px_11.png";
+PanoJS.CONTROL_IMAGE_ZOOMOUT  = "32px_minus.png";
+PanoJS.CONTROL_IMAGE_MAXIMIZE = "32px_show.png";
 
-PanoJS.CONTROL_IMAGE_ZOOMIN_TOUCH   = "images/64px_plus.png";
-PanoJS.CONTROL_IMAGE_ZOOM11_TOUCH   = "images/64px_11.png";
-PanoJS.CONTROL_IMAGE_ZOOMOUT_TOUCH  = "images/64px_minus.png";
-PanoJS.CONTROL_IMAGE_MAXIMIZE_TOUCH = "images/64px_show.png";
+PanoJS.CONTROL_IMAGE_ZOOMIN_TOUCH   = "64px_plus.png";
+PanoJS.CONTROL_IMAGE_ZOOM11_TOUCH   = "64px_11.png";
+PanoJS.CONTROL_IMAGE_ZOOMOUT_TOUCH  = "64px_minus.png";
+PanoJS.CONTROL_IMAGE_MAXIMIZE_TOUCH = "64px_show.png";
```

If I add the `images/` into panojs-2.0.0/controls.js in your branch, that fixes the issue and the icons load OK.
But I don't really understand why, since in the `master` branch, they don't exist there (you have reverted correctly)!
Maybe something else got changed and not reverted...?

2023-01-23 12:52 UTC, will-moore commented on omeroweb/webgateway/static/webgateway/js/ome.viewportImage.js
> +                staticBaseURL   : mediaroot+'3rdparty/panojs-2.0.0/',
I tracked it down to this change that didn't get reverted when you returned to `panojs-2.0.0` and that is breaking the icons.

2023-01-23 13:18 UTC, kyleBalisWest commented on omeroweb/webgateway/static/webgateway/js/ome.viewportImage.js
> +                staticBaseURL   : mediaroot+'3rdparty/panojs-2.0.0/',
Oh yeah I missed that, thanks for finding it @will-moore. It should be fixed now!

2023-01-24 12:38 UTC, pwalczysko approved these changes

2023-01-24 16:59 UTC, will-moore requested changes
All looks good - Just the auto-complete issues (and suggested fix) at https://github.com/ome/omero-web/pull/433#issuecomment-1396774881 to address

2023-01-26 17:57 UTC, will-moore commented
@sbesson That would mean that the web upgrade is a breaking change and you wouldn't want to upgrade omero-web without also upgrading mapr. But how to enforce that.
It adds complexity unnecessarily I think.
Just add `display: block` to `.ui-menu-item a` in dusty.css should fix it (going on my comment above)

2023-01-27 09:48 UTC, chris-allan commented
> That would mean that the web upgrade is a breaking change and you wouldn't want to upgrade omero-web without also upgrading mapr.

We are upgrading several core libraries in this PR and #435 is also likely to go in to the next version. These are both breaking changes in my opinion. Do you disagree?

Consequently, yes, I would expect you would not want to upgrade omero-web without also upgrading mapr, no? And you would want this new mapr version to depend on the at least the new minor version. This is the same pattern we followed for the Django 3.2 work in #356. Am I missing something here?

2023-01-27 13:00 UTC, will-moore commented
I guess I don't understand the objection to fixing the issue in this PR?

2023-01-30 15:36 UTC, sbesson commented
>  I guess I don't understand the objection to fixing the issue in this PR?

Having looked a bit the history, I found the root of this issue precedes this PR as turned out to also be a problem during the former jquery upgrade in #180. At the time, patches were introduced directly in the CSS to meet the expectations of the mapr plugin, more specifically in https://github.com/ome/omero-web/blob/efc042b7c836a28713835e1e0bc724cb8e40a2fe/omeroweb/webgateway/static/3rdparty/jquery-ui-1.12.1/css/jquery-ui.css#L133-L141 and https://github.com/ome/omero-web/blob/efc042b7c836a28713835e1e0bc724cb8e40a2fe/omeroweb/webgateway/static/3rdparty/jquery-ui-1.12.1/css/jquery-ui.css#L159-L163. In other terms, we have been maintaining a vendored fork of jquery-ui and more than the nature of the fix itself, my concern has to do with perpetuating this practice.

Let's assume another Web app developed by the community was relying on the internals of `d3` and using `d3.scale.linear` which has been dropped in the upgraded version. Would we consider introducing some form of compatibility layer in OMERO.web allowing them to continue using this API in the foreseeable future even as we keep upgrading the library?  In that case, I think we would all agree the maintenance cost is really high and the plugin should be responsible for upgrading its internals and making another release compatible with the new OMERO.web release. As far as I understand, the situation is no different for mapr which effectively relies on some jquery-ui styling which has been change upstream almost a decade ago.

Beyond this particular fix, paraphrasing @chris-allan, I also think we want to be transparent about the fact there are breaking changes associated with the library upgrades proposed here. I would be very careful about conveying the misleading idea that consumers/app developers can just upgrade OMERO.web without thinking about the nature of these changes and the implications on their own plugins. In many ways, having a handful of OMERO.web apps in our own ecosystem that also need to be updated and released is a healthy process as it forces us to think how to communicate the upgrade process to our community.

2023-01-30 16:54 UTC, will-moore commented
OK, I guess this PR is good to merge then

2023-01-31 09:50 UTC, knabar commented
Thanks everyone for the PR reviews!

2023-01-31 09:55 UTC, sbesson approved these changes

2023-02-09 13:04 UTC, merged