Add MultipleFileField to handle and clean multiple files
ome/omero-web pull request #465
Opened 2023-05-03 15:56 UTC by will-moore

Fixes #464

This adds the update suggested at the last link below to conform to the security release below:

https://github.com/ome/omero-web/pull/410
https://www.djangoproject.com/weblog/2023/may/03/security-releases/
https://github.com/django/django/commit/eed53d0011622e70b936e203005f0e6f4ac48965

To test:
 - Build should be green (using latest Django 3.2.19)
 - Multiple file upload should still be working

2023-05-04 12:40 UTC, sbesson requested changes
See https://github.com/ome/omero-web/pull/466 which exposes another underlying issue related to the validation of the files uploaded via the `FilesAnnotationForm` (and allows to create a scenario to test this PR).
While testing the two PRs together, it should be noted that this PR _requires_ Django 3.2.19 as the API for auto-setting  `multiple: true` when `allow_multiple_selected` is set to True was introduced in https://github.com/django/django/commit/eed53d0011622e70b936e203005f0e6f4ac48965. In other terms, with this PR and Django 3.2.18, the multiple selection is disabled. Django should be set to 3.2.19 as the minimum version via `setup.py`

2023-05-04 13:17 UTC, will-moore commented
Excluding to allow testing of #466 ahead of this...

--exclude

2023-05-04 15:44 UTC, will-moore commented
Testing on merge-ci:

 - upload 1 or more non-empty files works -> Creates FileAnnoations
 - upload multiple Files which includes an empty file first, last or middle (if 3) fails silently - (form is invalid).

2023-05-05 06:49 UTC, sbesson requested changes

2023-05-05 06:49 UTC, sbesson commented on omeroweb/webclient/forms.py
> +# Custom widget and validation for multiple file uploads
Having looked at how the code is constructed, it looks like the approach is do declare all custom widget/fields in `omeroweb.webclient.custom_forms` and import them here to construct the forms.

2023-05-05 06:49 UTC, sbesson commented on omeroweb/webclient/forms.py
> +    allow_multiple_selected = True
Might be worth adding a comment and/or a reference to the documentation explaining why we are subclassing these Django classes.

2023-05-05 09:05 UTC, dominikl commented
Functional test looks good 👍  If there's one empty file included in a multi file upload then none of the files get uploaded/attached, not even the non-empty ones. Is that expected?

2023-05-05 12:00 UTC, sbesson commented
@dominikl that's the expectation as per the new field class. If any of the files fails validation, then the entire multi-file upload is cancelled. 


The other place that uses a `FileField` is the photo upload in `My account` and this shows an informative message if an empty file is uploaded 

<img width="1202" alt="Screenshot 2023-05-05 at 12 58 02" src="https://user-images.githubusercontent.com/1355463/236452176-0bfccb95-e7ec-477a-a377-1e969b1d85dd.png">

@will-moore is there a way to propagate the error message to the user in the files annotation UI?

2023-05-05 14:38 UTC, dominikl commented
👍 I don't think either that it has to go into this PR, better get it out as soon as possible.

2023-05-09 10:09 UTC, sbesson approved these changes
The last commit follows the new recommendation from Django documentation with a new custom class and restores compatibility with Django 3.2.19.

The last commit will need to be retested functionally but from a code review perspective, no objection to moving forward with the current suggestion.

2023-05-09 10:42 UTC, knabar approved these changes
Code looks good to me

2023-05-09 13:34 UTC, will-moore commented
Running https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/1446/ to include latest changes... 
Built with https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-build/1402/
and deployed with https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-web/1659/

2023-05-10 09:39 UTC, pwalczysko commented
Tested on merge-ci, user-3. From jenkins, this PR is included on https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/1447/console


```
Merged PRs:
  - PR 425 will-moore 'Add hook for mapr or other app to extend webclient main page'
  - PR 456 kkoz 'Allow Tiled Image Histograms'
  - PR 462 will-moore 'OME.formatDate handles null input'
  - PR 465 will-moore 'Add MultipleFileField to handle and clean multiple files'
  - PR 467 knabar 'Add change log for 5.20.0'
  - PR 469 will-moore 'Temp setGroupForSession to edit current group'
 ```

The test:
1. Create an empty file using ``touch`` on the cli and try to attach it in the Attachments harmonica of webclient. 
2. Try to attach the empty file also with other, non-empty files
3. Try to upload the empty file as a photo in user settings of web UI

The tests went as expected, the file upload was rejected in all cases where the empty file was selected, either with non-empty files or alone.
The upload of photos and files (non-empty ones) still works.

LGTM

2023-05-10 09:40 UTC, pwalczysko approved these changes

2023-05-10 09:49 UTC, jburel approved these changes

2023-05-10 09:49 UTC, merged