Inherit annotation support
ome/omero-web pull request #508
Opened 2023-11-01 17:36 UTC by Tom-TBT

This PR is to discuss the implementation of support for inherited annotations.

On the webclient api front, this PR include changes to `api_annotations`, which now also includes a field on inherited annotations in the returned JSON:
``` json
{
  "annotations": [],    // list of annotations (no change)
  "experimenters": [],  // list of experimenters (no change)
  "inherited": { // new
      "annotations": [], // list of inherited annotations (no duplicates)
      "inheritors": {}   // annID dictionnary of inheritors. Same style as annotations.link.parent
}
```

To use it, you would have to "unpack" the inherited annotations to populate a list of annotation, one for each matching inheritor. The annotations are then processed normally.

For example, I used this changes to add the results in the main UI of the Key-Value pairs, and look like that (from a dataset object):
![image](https://github.com/ome/omero-web/assets/10853316/2995733f-d464-4693-8383-37545f30957e)

See other example with parallel PR on support with OMERO.figure

I had to implement a recursive function to list parents of objects, because `obj.getAncestry()` does not go through all links if an image is inside multiple datasets. Was there a better way to do that ?

I hope that it's not too hacky in the way it's implemented. Looking forward from comment / feedback

2023-11-02 13:15 UTC, will-moore commented
Thanks for the PR @Tom-TBT. I gave it a quick test locally and seems to be working well. 
It's definitely useful functionality. I have a couple of broad concerns:
 - How to handle the UI space: it's possible that if this is always shown that it will be annoying for those who don't want to see it - It can push the Image KVP further down the page, possibly quite a long way. At the moment it gets in-between the editable KVP section and the toolbar for working with that.
 - API changes: I think that the addition of parent KVP in the `api_annotations` endpoint should be optional (disabled by default). I didn't quite understand the `inheritors` (or the need for it) looking at your comment above, but in testing this becomes clearer, since it's possible that not all the selected objects are inherited from the same parents. E.g. here, the parent Dataset KVP only applies to some of the images:

![Screenshot 2023-11-02 at 12 58 01](https://github.com/ome/omero-web/assets/900055/94af7a1e-e9ca-43d7-9460-7fa640792296)

However, I think the summary needs some work: In that view `5 Annotations linked to: 5 objects` is not quite true since it's one KVP on the one Dataset. Maybe `Dataset:55:CDK5RAP2-C linked to 5 objects`.
And the same is true in the tooltip:

![Screenshot 2023-11-02 at 12 58 57](https://github.com/ome/omero-web/assets/900055/ac148fc4-d41a-44db-90a1-1a23ea1945a0)

I was trying to think of a way that the JSON format could be more generic (less specific to the particular UI that you want to show here), but it's hard to do that without adding a lot more data to the response (e.g. all P/D/I links) or requiring the client to make multiple calls. E.g lookup the P/D/I links and then make a call to include parent KVP e.g.

`webclient/api/annotations/?type=map&image=10&image=11&dataset=2&project=3`

This wouldn't need any api changes.

2023-11-02 16:31 UTC, Tom-TBT commented
> How to handle the UI space

I thought it worked but apparently not: It was supposed to list the KV from the topmost to the lowest:
* Plate -> Dataset
* Screen -> Plate -> Acquisition -> Well

In any case, we could leave the current object annotation on top, and then list the inherited below in reverse order (to avoid having the order change depending on which object in the hierarchy is selected).

>  it's possible that not all the selected objects are inherited from the same parents

And that's the case too for OMERO.figure, where images can come from wells & datasets


> Dataset:55:CDK5RAP2-C linked to 5 objects

Maybe then gets crowded with the name. Should we drop the name?
And with the tooltip, that's some more UI changes required in the HTML template then!

> webclient/api/annotations/?type=map&image=10&image=11&dataset=2&project=3

Then we need to know first the hierarchy of each object queried, and tie back all the parent annotations in the response to the children. 

Are you able to get the full hierarchy without changing the API?

I saw the `api_parent_links` : `webclient/api/parent_links/?image=11`
It supports only `parent_types = {"image": "dataset", "dataset": "project", "plate": "screen"}` right now (so wouldn't work for plates), but, adding the implementation for `{"image": ["dataset", "well"], "well": "acquisition", "acquisition": "plate"}` sounds better than the questionable changes I made in `api_annotation`


Thanks for the feedback!

2023-11-03 15:28 UTC, joshmoore commented
There's not yet anything to identify whether or not a parent Annotation should apply to a child, right? I.e. all are inherited.

2023-11-06 09:06 UTC, Tom-TBT commented
@joshmoore I don't know if anything exists to say that. Though objects have the `listParent` and `listChildren` methods ;)

But to add to your comment, I could think of two flags:
* inherit from parents
* apply annotations to children

2023-11-09 15:42 UTC, will-moore commented
Looking better:

![Screenshot 2023-11-09 at 15 41 16](https://github.com/ome/omero-web/assets/900055/2de84466-2960-45af-a773-d113224fb5ca)

2023-11-15 20:43 UTC, will-moore commented
I think this is working pretty well now...

![Screenshot 2023-11-14 at 12 55 18](https://github.com/ome/omero-web/assets/900055/4102b01b-140f-40f6-b653-5d33bbdc2cbf)

Maybe some tweaks to the API:

 - for the url parameter I think `?parents=true` (instead of `?parents=yes`). This is what we've done elsewhere.
 - for the JSON, I think that `"parents": {"annotations":[] }` might be better than `"inherited": {"annotations": []}`, since this is listing the annotations on the parents. Also more consistent with the URL parameter.
 - I'm not sure about `"inheritors"` key. Maybe something else to indicate the relationship. Perhaps `"ancestors"` or `"links"` or `"lineage"'.

So I'm pretty happy with this PR. Haven't tested Screen/Plate/Well yet. 
But I'd be interested in hearing from @knabar

2023-11-17 12:52 UTC, knabar commented
Looking good to me, I just have a question regarding users who may have lots of annotations, but no use case for seeing these extra annotations in the UI.

* What is the performance impact when there are lots of annotations on the parents objects?
* What is the UI impact for someone who does not need to see them?  (For example, on the scale from no impact via distracting or annoying all the way to pushing information they'd rather see out of the way?

2023-11-23 11:02 UTC, will-moore commented
@Tom-TBT I imported a lot of fake files into the merge-ci server so you can test performance. You can see (and select) 500 of them by using search. E.g. `/webclient/search/?search_query=fake`.
They are currently all in one Dataset and don't have KVP - let me know if you want me to run some script or annotate them in some way?

2023-11-24 17:06 UTC, Tom-TBT commented
I made some test on the time it takes for the annotation query. I did it with:
* All images in one dataset, one key-value pair on each image
* 100 images in 100 dataset, one kv per image
* 100 images in 100 dataset, one kv per image and one per dataset
* 100 images in 100 dataset in 100 projects, one kv per image and one per dataset
* 100 images in 100 dataset in 100 projects, one kv per image, one per dataset, one per project

![image](https://github.com/ome/omero-web/assets/10853316/6a1a84c8-c673-482b-b57e-ce7fb544e34e)

The time increases when I increase the number of annotations, not when I increase the number of dataset or project.

The increase of the response time increase linearly with the number of image selected, which is also expected.

Regarding the display in the UI, I'm able to select up to ~330 images (after that, the query is too long, could be compressed to image=1,2,3). With that many images and all the annotations I have from the previous test (with even extra KV on the other 230 images), the page seems ok:
![image](https://github.com/ome/omero-web/assets/10853316/fc17a416-c7b2-41dc-9bbb-ea94ba3aa01c)

2023-11-27 22:17 UTC, Tom-TBT commented
I found an issue with HCS data. When annotations on the Well or on the PlateAcquisition, the display in the webclient of KV fails. This is because there are no name for Well or Run (name is optional for Run) while it should print the name of the parent object (Added on Project XYZ)

A quickfix is to set the `link.parent.name` to `""`, but it would be better to show the "name" of the well, or to build the run name ("Run "+ run_id). I need a little bit more time to figure where to do it, and without adding too much extra loading just for that feature (Well coordinates depends on the plate object).

2023-12-05 11:56 UTC, Tom-TBT commented
Last commit fixes the name issue of the Well and PlateAcquisition by adding their name to the JSON response.

From merge-ci:
![image](https://github.com/ome/omero-web/assets/10853316/1b8d5fe1-595a-4b71-9ea5-ec128a9bd36c)

Before/after commit, JSON for the `annotation link.parent`:

Well:
```json
"parent": {
    "id": 12992,
    "class": "WellI",
}

"parent": {
    "id": 12992,
    "class": "WellI",
    "name": "B2"
}
```

PlateAcquisition (case with name not set, as it's an optional property):
```json
"parent": {
    "id": 11052,
    "class": "PlateAcquisitionI",
    "name": null
}

"parent": {
    "id": 11052,
    "class": "PlateAcquisitionI",
    "name": "Run 11052"
}
```

2023-12-06 15:19 UTC, will-moore commented
This is working now for Plates/Wells/Images...
Screenshot shows selection of Images - right panel shows KVP on Images, Wells and Plate:

![Screenshot 2023-12-06 at 14 46 27](https://github.com/ome/omero-web/assets/900055/d6de1ca9-ef4c-48c4-829d-5ea93b1fc900)

Just a couple of minor points about tooltips...

There's a missing line-break after the 1st row of the tooltips. `Well ID: ...` should be on it's own line.

The `Inherited By` section is shown in the first screenshot below, and it's useful because it tells you which Images the KVP applies to. But it's not shown for the 2nd screenshot where I've only selected a single Image from each Well. I think it would still be useful here.

![Screenshot 2023-12-06 at 15 13 01](https://github.com/ome/omero-web/assets/900055/08ce8722-458f-4c3a-958e-32b880d2d8e5)

![Screenshot 2023-12-06 at 15 13 25](https://github.com/ome/omero-web/assets/900055/174b63ad-bed9-4f5e-b096-1e0ed6fafa1f)

2023-12-13 16:42 UTC, pwalczysko requested changes
2 RFEs:

1. Remove the "You are viewing an inherited annotation" from the tooltip, it is not necessary and it is both unclear&daunting to the user.
2. Make a distinction in the tooltip based on whether one or more images are selected. if only one image is selected, the "inherited by" in the tooltip is not shown. If more images are selected, then "inherited by" is shown. 

Otherwise lgtm.

2023-12-15 11:28 UTC, Tom-TBT commented
Hello Petr, 
thank you for the input, I modified the tooltip accordingly.:

One object selected, no "inherited by" section:
![image](https://github.com/ome/omero-web/assets/10853316/95cbdd8d-f9f5-4b86-abb8-4f3e9705d2c4)

More than one object, selected, "inherited by" section:
![image](https://github.com/ome/omero-web/assets/10853316/861413c3-d0a3-4bb8-8344-2514a840fe0b)

 "inherited by" also shows when the annotations are inherited by a single object (as formulated in the previous request from Will):
![image](https://github.com/ome/omero-web/assets/10853316/32166bf1-238c-4939-92ee-1818d5eaa3a6)

2023-12-15 16:31 UTC, will-moore approved these changes
This is looking good and working fine for me

2023-12-19 11:39 UTC, merged